name = "TERRA"
uuid = "8a405caf-3569-4c97-876d-2cf871ca8799"
authors = ["Amin Taziny"]
version = "0.7.0"

[deps]
DiffEqBase = "2b5f629d-d688-5b77-993f-72d75c75574e"
DifferentialEquations = "0c46a032-eb83-5123-abaf-570d42b7fbaa"
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"

[compat]
Aqua = "0.8"
DiffEqBase = "6.190.2"
DifferentialEquations = "7.16.1"
DocStringExtensions = "0.9.5"
Libdl = "1.11.0"
Printf = "1.11.0"
Test = "1"
julia = "1.12"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Aqua", "Test"]
