name = "TERRA"
uuid = "8a405caf-3569-4c97-876d-2cf871ca8799"
version = "0.8.0"
authors = ["Amin Taziny"]

[deps]
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"
OrdinaryDiffEq = "1dea7af3-3e70-54e6-95c3-0bf5283fa5ed"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
SciMLBase = "0bca4576-84f4-4d90-8ffe-ffa030f20462"

[compat]
Aqua = "0.8"
DocStringExtensions = "0.9.5"
Libdl = "1.11.0"
OrdinaryDiffEq = "6.107.0"
Printf = "1.11.0"
SciMLBase = "2.139.0"
Test = "1"
julia = "1.12"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Aqua", "Test"]
